// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxappmetricsapitest.proxies;

public class Metrics
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject metricsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxAppMetricsAPITest.Metrics";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MetricsPayload("MetricsPayload"),
		Timestamp("Timestamp");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Metrics(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxAppMetricsAPITest.Metrics"));
	}

	protected Metrics(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject metricsMendixObject)
	{
		if (metricsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxAppMetricsAPITest.Metrics", metricsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxAppMetricsAPITest.Metrics");

		this.metricsMendixObject = metricsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Metrics.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxappmetricsapitest.proxies.Metrics initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxappmetricsapitest.proxies.Metrics.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxappmetricsapitest.proxies.Metrics initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxappmetricsapitest.proxies.Metrics(context, mendixObject);
	}

	public static mxappmetricsapitest.proxies.Metrics load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxappmetricsapitest.proxies.Metrics.initialize(context, mendixObject);
	}

	public static java.util.List<mxappmetricsapitest.proxies.Metrics> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxappmetricsapitest.proxies.Metrics> result = new java.util.ArrayList<mxappmetricsapitest.proxies.Metrics>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxAppMetricsAPITest.Metrics" + xpathConstraint))
			result.add(mxappmetricsapitest.proxies.Metrics.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MetricsPayload
	 */
	public final java.lang.String getMetricsPayload()
	{
		return getMetricsPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricsPayload
	 */
	public final java.lang.String getMetricsPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricsPayload.toString());
	}

	/**
	 * Set value of MetricsPayload
	 * @param metricspayload
	 */
	public final void setMetricsPayload(java.lang.String metricspayload)
	{
		setMetricsPayload(getContext(), metricspayload);
	}

	/**
	 * Set value of MetricsPayload
	 * @param context
	 * @param metricspayload
	 */
	public final void setMetricsPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metricspayload)
	{
		getMendixObject().setValue(context, MemberNames.MetricsPayload.toString(), metricspayload);
	}

	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return metricsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxappmetricsapitest.proxies.Metrics that = (mxappmetricsapitest.proxies.Metrics) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxAppMetricsAPITest.Metrics";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
