// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxappmetricstest.proxies;

public class MetricTestData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject metricTestDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxAppMetricsTest.MetricTestData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MetricName("MetricName"),
		MetricValue("MetricValue"),
		MetricTagName("MetricTagName"),
		MetricTagValue("MetricTagValue"),
		MetricTags("MetricTags"),
		IsKPI("IsKPI"),
		MetricTimestamp("MetricTimestamp");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MetricTestData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxAppMetricsTest.MetricTestData"));
	}

	protected MetricTestData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject metricTestDataMendixObject)
	{
		if (metricTestDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxAppMetricsTest.MetricTestData", metricTestDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxAppMetricsTest.MetricTestData");

		this.metricTestDataMendixObject = metricTestDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MetricTestData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxappmetricstest.proxies.MetricTestData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxappmetricstest.proxies.MetricTestData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxappmetricstest.proxies.MetricTestData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxappmetricstest.proxies.MetricTestData(context, mendixObject);
	}

	public static mxappmetricstest.proxies.MetricTestData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxappmetricstest.proxies.MetricTestData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MetricName
	 */
	public final java.lang.String getMetricName()
	{
		return getMetricName(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricName
	 */
	public final java.lang.String getMetricName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricName.toString());
	}

	/**
	 * Set value of MetricName
	 * @param metricname
	 */
	public final void setMetricName(java.lang.String metricname)
	{
		setMetricName(getContext(), metricname);
	}

	/**
	 * Set value of MetricName
	 * @param context
	 * @param metricname
	 */
	public final void setMetricName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metricname)
	{
		getMendixObject().setValue(context, MemberNames.MetricName.toString(), metricname);
	}

	/**
	 * @return value of MetricValue
	 */
	public final java.math.BigDecimal getMetricValue()
	{
		return getMetricValue(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricValue
	 */
	public final java.math.BigDecimal getMetricValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MetricValue.toString());
	}

	/**
	 * Set value of MetricValue
	 * @param metricvalue
	 */
	public final void setMetricValue(java.math.BigDecimal metricvalue)
	{
		setMetricValue(getContext(), metricvalue);
	}

	/**
	 * Set value of MetricValue
	 * @param context
	 * @param metricvalue
	 */
	public final void setMetricValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal metricvalue)
	{
		getMendixObject().setValue(context, MemberNames.MetricValue.toString(), metricvalue);
	}

	/**
	 * @return value of MetricTagName
	 */
	public final java.lang.String getMetricTagName()
	{
		return getMetricTagName(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricTagName
	 */
	public final java.lang.String getMetricTagName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricTagName.toString());
	}

	/**
	 * Set value of MetricTagName
	 * @param metrictagname
	 */
	public final void setMetricTagName(java.lang.String metrictagname)
	{
		setMetricTagName(getContext(), metrictagname);
	}

	/**
	 * Set value of MetricTagName
	 * @param context
	 * @param metrictagname
	 */
	public final void setMetricTagName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metrictagname)
	{
		getMendixObject().setValue(context, MemberNames.MetricTagName.toString(), metrictagname);
	}

	/**
	 * @return value of MetricTagValue
	 */
	public final java.lang.String getMetricTagValue()
	{
		return getMetricTagValue(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricTagValue
	 */
	public final java.lang.String getMetricTagValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricTagValue.toString());
	}

	/**
	 * Set value of MetricTagValue
	 * @param metrictagvalue
	 */
	public final void setMetricTagValue(java.lang.String metrictagvalue)
	{
		setMetricTagValue(getContext(), metrictagvalue);
	}

	/**
	 * Set value of MetricTagValue
	 * @param context
	 * @param metrictagvalue
	 */
	public final void setMetricTagValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metrictagvalue)
	{
		getMendixObject().setValue(context, MemberNames.MetricTagValue.toString(), metrictagvalue);
	}

	/**
	 * @return value of MetricTags
	 */
	public final java.lang.String getMetricTags()
	{
		return getMetricTags(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricTags
	 */
	public final java.lang.String getMetricTags(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricTags.toString());
	}

	/**
	 * Set value of MetricTags
	 * @param metrictags
	 */
	public final void setMetricTags(java.lang.String metrictags)
	{
		setMetricTags(getContext(), metrictags);
	}

	/**
	 * Set value of MetricTags
	 * @param context
	 * @param metrictags
	 */
	public final void setMetricTags(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metrictags)
	{
		getMendixObject().setValue(context, MemberNames.MetricTags.toString(), metrictags);
	}

	/**
	 * @return value of IsKPI
	 */
	public final java.lang.Boolean getIsKPI()
	{
		return getIsKPI(getContext());
	}

	/**
	 * @param context
	 * @return value of IsKPI
	 */
	public final java.lang.Boolean getIsKPI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsKPI.toString());
	}

	/**
	 * Set value of IsKPI
	 * @param iskpi
	 */
	public final void setIsKPI(java.lang.Boolean iskpi)
	{
		setIsKPI(getContext(), iskpi);
	}

	/**
	 * Set value of IsKPI
	 * @param context
	 * @param iskpi
	 */
	public final void setIsKPI(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iskpi)
	{
		getMendixObject().setValue(context, MemberNames.IsKPI.toString(), iskpi);
	}

	/**
	 * @return value of MetricTimestamp
	 */
	public final java.util.Date getMetricTimestamp()
	{
		return getMetricTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricTimestamp
	 */
	public final java.util.Date getMetricTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MetricTimestamp.toString());
	}

	/**
	 * Set value of MetricTimestamp
	 * @param metrictimestamp
	 */
	public final void setMetricTimestamp(java.util.Date metrictimestamp)
	{
		setMetricTimestamp(getContext(), metrictimestamp);
	}

	/**
	 * Set value of MetricTimestamp
	 * @param context
	 * @param metrictimestamp
	 */
	public final void setMetricTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date metrictimestamp)
	{
		getMendixObject().setValue(context, MemberNames.MetricTimestamp.toString(), metrictimestamp);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return metricTestDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxappmetricstest.proxies.MetricTestData that = (mxappmetricstest.proxies.MetricTestData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxAppMetricsTest.MetricTestData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
