// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxappmetricstest.proxies;

public class Metric
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject metricMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxAppMetricsTest.Metric";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MetricName("MetricName"),
		MetricType("MetricType"),
		MetricValue("MetricValue"),
		Tags("Tags"),
		IsKpi("IsKpi");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Metric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxAppMetricsTest.Metric"));
	}

	protected Metric(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject metricMendixObject)
	{
		if (metricMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxAppMetricsTest.Metric", metricMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxAppMetricsTest.Metric");

		this.metricMendixObject = metricMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Metric.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxappmetricstest.proxies.Metric initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxappmetricstest.proxies.Metric.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxappmetricstest.proxies.Metric initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxappmetricstest.proxies.Metric(context, mendixObject);
	}

	public static mxappmetricstest.proxies.Metric load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxappmetricstest.proxies.Metric.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MetricName
	 */
	public final java.lang.String getMetricName()
	{
		return getMetricName(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricName
	 */
	public final java.lang.String getMetricName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricName.toString());
	}

	/**
	 * Set value of MetricName
	 * @param metricname
	 */
	public final void setMetricName(java.lang.String metricname)
	{
		setMetricName(getContext(), metricname);
	}

	/**
	 * Set value of MetricName
	 * @param context
	 * @param metricname
	 */
	public final void setMetricName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metricname)
	{
		getMendixObject().setValue(context, MemberNames.MetricName.toString(), metricname);
	}

	/**
	 * Set value of MetricType
	 * @param metrictype
	 */
	public final mxappmetricstest.proxies.MetricType getMetricType()
	{
		return getMetricType(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricType
	 */
	public final mxappmetricstest.proxies.MetricType getMetricType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MetricType.toString());
		if (obj == null)
			return null;

		return mxappmetricstest.proxies.MetricType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MetricType
	 * @param metrictype
	 */
	public final void setMetricType(mxappmetricstest.proxies.MetricType metrictype)
	{
		setMetricType(getContext(), metrictype);
	}

	/**
	 * Set value of MetricType
	 * @param context
	 * @param metrictype
	 */
	public final void setMetricType(com.mendix.systemwideinterfaces.core.IContext context, mxappmetricstest.proxies.MetricType metrictype)
	{
		if (metrictype != null)
			getMendixObject().setValue(context, MemberNames.MetricType.toString(), metrictype.toString());
		else
			getMendixObject().setValue(context, MemberNames.MetricType.toString(), null);
	}

	/**
	 * @return value of MetricValue
	 */
	public final java.lang.Long getMetricValue()
	{
		return getMetricValue(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricValue
	 */
	public final java.lang.Long getMetricValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.MetricValue.toString());
	}

	/**
	 * Set value of MetricValue
	 * @param metricvalue
	 */
	public final void setMetricValue(java.lang.Long metricvalue)
	{
		setMetricValue(getContext(), metricvalue);
	}

	/**
	 * Set value of MetricValue
	 * @param context
	 * @param metricvalue
	 */
	public final void setMetricValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long metricvalue)
	{
		getMendixObject().setValue(context, MemberNames.MetricValue.toString(), metricvalue);
	}

	/**
	 * @return value of Tags
	 */
	public final java.lang.String getTags()
	{
		return getTags(getContext());
	}

	/**
	 * @param context
	 * @return value of Tags
	 */
	public final java.lang.String getTags(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tags.toString());
	}

	/**
	 * Set value of Tags
	 * @param tags
	 */
	public final void setTags(java.lang.String tags)
	{
		setTags(getContext(), tags);
	}

	/**
	 * Set value of Tags
	 * @param context
	 * @param tags
	 */
	public final void setTags(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tags)
	{
		getMendixObject().setValue(context, MemberNames.Tags.toString(), tags);
	}

	/**
	 * @return value of IsKpi
	 */
	public final java.lang.Boolean getIsKpi()
	{
		return getIsKpi(getContext());
	}

	/**
	 * @param context
	 * @return value of IsKpi
	 */
	public final java.lang.Boolean getIsKpi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsKpi.toString());
	}

	/**
	 * Set value of IsKpi
	 * @param iskpi
	 */
	public final void setIsKpi(java.lang.Boolean iskpi)
	{
		setIsKpi(getContext(), iskpi);
	}

	/**
	 * Set value of IsKpi
	 * @param context
	 * @param iskpi
	 */
	public final void setIsKpi(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iskpi)
	{
		getMendixObject().setValue(context, MemberNames.IsKpi.toString(), iskpi);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return metricMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxappmetricstest.proxies.Metric that = (mxappmetricstest.proxies.Metric) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxAppMetricsTest.Metric";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
